name: Terraform Apply (Dev)

on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Approve Terraform Apply'
        required: true
        default: 'no'

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.4" # Same version as plan

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          if [[ "${{ github.event.inputs.approval }}" == "yes" ]]; then
            terraform apply -auto-approve tfplan
          else
            echo "Terraform apply was not approved"
            exit 1
          fi
