name: Terraform Plan (Dev)

on:
  push:
    branches:
      - main

permissions:  # 👈 ADD THIS BLOCK
  id-token: write   # Required for GitHub to request the OIDC token
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.4"

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::354918385395:role/GitHubActionsOIDCRole
          aws-region:            us-east-1

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: Terraform Plan
        working-directory: infrastructure
        run: |
          terraform plan -input=false \
            -var-file="terraform.tfvars" \
            -out=tfplan
